---
title: "Final_XSTK"
author: "Tran Hong Phuc"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
# Them thu vien
library(dplyr)
library(tidyr)
library(ggplot2)
library(pander)
library(nortest)
```

```{r}
Intel_CPUs<-read.csv(".\\input\\Intel_CPUs.csv")
```

```{r}
# Dieu chinh lai cac o trong va du lieu la thanh NA
Intel_CPUs <- replace(Intel_CPUs, Intel_CPUs == "", NA)
Intel_CPUs <- replace(Intel_CPUs, Intel_CPUs == "N/A", NA)

colSums(is.na(Intel_CPUs))
```

```{r}
# Sap xep cac bien theo chieu tang dan cua gia tri khuyet
na_counts <- colSums(is.na(Intel_CPUs))
sort <- Intel_CPUs[, order(na_counts)]
colSums(is.na(sort))
```

```{r}
# Tao data frame
data <- Intel_CPUs %>% select('Vertical_Segment', 'Status', 'nb_of_Cores',
                              'Processor_Base_Frequency', 'TDP', 'Lithography',
                              'Launch_Date', 'nb_of_Threads','Max_Memory_Size', 'Instruction_Set')
colSums(is.na(data))
head(data)
str(data)
```

```{r}
# Xu ly dinh dang

# Processor_Base_Frequency
data <- separate(data, Processor_Base_Frequency, c("P_B_F_val", "P_B_F_unit"), sep = " " )
data$P_B_F_val <- as.numeric(data$P_B_F_val)
table(data$P_B_F_unit)
data$P_B_F_val<-ifelse(data$P_B_F_unit == "MHz",
                                          data$P_B_F_val/1000,
                                          data$P_B_F_val)
data <- select(data, -P_B_F_unit)
colnames(data)[colnames(data) == "P_B_F_val"] <- "P_B_Frequency"
```

```{r}
# TDP
data <- separate(data, TDP, c("TDP_val", "TDP_unit"), sep = " " )
data$TDP_val <- as.numeric(data$TDP_val)
table(data$TDP_unit)
data <- select(data, -TDP_unit)
colnames(data)[colnames(data) == "TDP_val"] <- "TDP"
```

```{r}
# Lithography
data <- separate(data, Lithography, c("Lithography_val", "Lithography_unit"), sep = " " )
data$Lithography_val <- as.integer(data$Lithography_val)
table(data$Lithography_unit)
data <- select(data, -Lithography_unit)
colnames(data)[colnames(data) == "Lithography_val"] <- "Lithography"
```

```{r}
# Launch_Date
data <- separate(data, Launch_Date, c("Launch_Quarter", "Launch_Year"), sep = "'" )
data$Launch_Year<-as.integer(data$Launch_Year)
data$Launch_Year<-data$Launch_Year + 2000 
table(data$Launch_Year)
data<-select(data, -Launch_Quarter)
```

```{r}
# Max_Memory_Size
data <- separate(data, Max_Memory_Size, c("M_Memory_Size_val", "M_Memory_Size_unit"), sep = " " )
data$M_Memory_Size_val <- as.numeric(data$M_Memory_Size_val)
table(data$M_Memory_Size_unit)
data$M_Memory_Size_val <- ifelse(data$M_Memory_Size_unit == "TB",
                                 data$M_Memory_Size_val*1000,
                                 data$M_Memory_Size_val)
data <- select(data, -M_Memory_Size_unit)
colnames(data)[colnames(data) == "M_Memory_Size_val"] <- "M_Memory_Size"
```
```{r}
str(data)
data$Vertical_Segment <- factor(data$Vertical_Segment)
data$Status <- factor(data$Status)
```

```{r}
data$Instruction_Set<-ifelse(data$Instruction_Set == "32-bit", '1', data$Instruction_Set)
data$Instruction_Set<-ifelse(data$Instruction_Set == "Itanium 64-bit", '2', data$Instruction_Set)
data$Instruction_Set<-ifelse(data$Instruction_Set == "64-bit", '3', data$Instruction_Set)
data$Instruction_Set<-as.numeric(data$Instruction_Set)
table(data$Instruction_Set)
```

```{r}
# Xu ly du lieu khuyet
apply(is.na(data), 2, mean)

# Ham dung replace NA thanh median
replace_na_with_median <- function(x) {
  median_value <- median(x, na.rm = TRUE)
  x[is.na(x)] <- median_value
  return(x)
}
```

```{r}
# Voi cac bien dinh luong
data <- data %>%
  group_by(Vertical_Segment) %>%
  mutate(across(c('nb_of_Cores', 'TDP', 'Lithography',
                  'Launch_Year', 'nb_of_Threads', 'M_Memory_Size',
                  'P_B_Frequency'), 
                replace_na_with_median)) 
# Voi cac bien dinh tinh
data <- na.omit(data)
# Kiem tra lai
apply(is.na(data), 2, mean)
```

```{r}
# Tim va xu ly Outliner
table(data$Vertical_Segment)
table(data$Status)


# Ham ve boxplot de nhin thay gia tri ngoai lai phan nhom theo V_S
draw_boxplot <- function(data) {
  a <- ggplot(data, aes(y = nb_of_Cores, x = Vertical_Segment, fill = Vertical_Segment)) +
    stat_boxplot(geom = "errorbar", width = 0.2) +
    geom_boxplot(outlier.color = "red", na.rm = TRUE) +
    labs(title = "Cores", y = "Number of Cores", x = "")
  
  b <- ggplot(data, aes(y = P_B_Frequency, x = Vertical_Segment, fill = Vertical_Segment)) +
    stat_boxplot(geom = "errorbar", width = 0.2) +
    geom_boxplot(outlier.color = "red", na.rm = TRUE) +
    labs(title = "Processor Base Frequency", y = "Processor Base Frequency", x = "")
  
  c <- ggplot(data, aes(y = TDP, x = Vertical_Segment, fill = Vertical_Segment)) +
    stat_boxplot(geom = "errorbar", width = 0.2) +
    geom_boxplot(outlier.color = "red", na.rm = TRUE) +
    labs(title = "TDP", y = "TDP", x = "")
  
  d <- ggplot(data, aes(y = Lithography, x = Vertical_Segment, fill = Vertical_Segment)) +
    stat_boxplot(geom = "errorbar", width = 0.2) +
    geom_boxplot(outlier.color = "red", na.rm = TRUE) +
    labs(title = "Lithography", y = "Lithography", x = "")
  
  e <- ggplot(data, aes(y = Launch_Year, x = Vertical_Segment, fill = Vertical_Segment)) +
    stat_boxplot(geom = "errorbar", width = 0.2) +
    geom_boxplot(outlier.color = "red", na.rm = TRUE) +
    labs(title = "Launch Year", y = "Launch Year", x = "")
  
  f <- ggplot(data, aes(y = nb_of_Threads, x = Vertical_Segment, fill = Vertical_Segment)) +
    stat_boxplot(geom = "errorbar", width = 0.2) +
    geom_boxplot(outlier.color = "red", na.rm = TRUE) +
    labs(title = "Threads", y = "Number of Threads", x = "")
  
  g <- ggplot(data, aes(y = M_Memory_Size, x = Vertical_Segment, fill = Vertical_Segment)) +
    stat_boxplot(geom = "errorbar", width = 0.2) +
    geom_boxplot(outlier.color = "red", na.rm = TRUE) +
    labs(title = "Max Memory size", y = "Max memory size", x = "")
  
  gridExtra::grid.arrange(a, b, c, d, e, f, g, ncol = 2)
}

draw_boxplot(data)
```

```{r}
# Ham xu ly ngoai lai bang phuong phap dua ngoai lai ve gioi han tren/duoi
remove_outliers <- function(x) {
  Q1 <- quantile(x, 0.25, na.rm = TRUE)
  Q3 <- quantile(x, 0.75, na.rm = TRUE)
  IQR_value <- Q3 - Q1
  lower_limit <- Q1 - 1.5 * IQR_value
  upper_limit <- Q3 + 1.5 * IQR_value
  x[x < lower_limit] <- lower_limit
  x[x > upper_limit] <- upper_limit
  return(x)
}

data <- data %>%
  group_by(Vertical_Segment) %>%
  mutate(across(c('nb_of_Cores',
                  'TDP', 'Lithography',
                  'Launch_Year', 'nb_of_Threads', 'M_Memory_Size',
                  'P_B_Frequency'), 
                remove_outliers)) 

draw_boxplot(data)
```

```{r}
# Ve bieu do tan so va nhan xet phan phoi cac bien dinh luong lien tuc
ggplot(data, aes(x = P_B_Frequency)) +
    geom_histogram(fill = "3", color = "black", binwidth = 0.1) +
    labs(title = "Processor Base Frequency", x = "Value", y = "Frequency")
```

```{r}
ggplot(data, aes(y = P_B_Frequency, x = Vertical_Segment, fill = Vertical_Segment)) +
    stat_boxplot(geom = "errorbar", width = 0.2) +
    geom_boxplot(outlier.color = "red", na.rm = TRUE) +
    labs(y = "Processor Base Frequency", x = "")
```


```{r}
# Bieu do phan tan
ggplot(data, aes(y = Lithography, size = P_B_Frequency, x = Launch_Year, color = Vertical_Segment)) +
        geom_point() +
        scale_size_continuous(range = c(1, 5)) +
        labs(y = "Lithography", size = "P_B_Frequency", x = "Launch Year", color = "Vertical Segment")

ggplot(data, aes(x = Launch_Year, y = TDP, size = P_B_Frequency, color = Status)) +
  geom_point() +
  scale_size_continuous(range = c(1, 5)) +
  labs(x = "Launch Year", y = "TDP", color = "Status", size = "P_B_Frequency")

ggplot(data, aes(x = nb_of_Cores, size = P_B_Frequency, color = Vertical_Segment, y = nb_of_Threads)) +
  geom_point() +
  scale_size_continuous(range = c(1, 5)) +
  labs(x = "Cores", size = "P_B_Frequency", y = "Threads")

ggplot(data, aes(x = nb_of_Cores, size = P_B_Frequency, color = Status, y = nb_of_Threads)) +
  geom_point() +
  scale_size_continuous(range = c(1, 5)) +
  labs(size = "P_B_Frequency", y = "Threads")

ggplot(data, aes(x = M_Memory_Size, y = TDP, color = Status, size = P_B_Frequency)) +
  geom_point() +
  scale_size_continuous(range = c(1, 5)) +
  labs(x = "Max Memory Size", size = "P_B_Frequency", y = "TDP", color = "Status")


```

```{r}
# Bang cac gia tri thong keke
by(data$P_B_Frequency, data$Vertical_Segment, summary)
```

```{r}
by(data$P_B_Frequency, data$Status, summary)
```


```{r}
#kiểm tra giả định 1
av_residual <- rstandard(aov(P_B_Frequency  ~ nb_of_Cores* Vertical_Segment, data = data))

ad.test(av_residual)
```

```{r}
#kiem tra giả định 2 :

levene_test <- car::leveneTest(P_B_Frequency ~ Vertical_Segment*as.factor(nb_of_Cores), data = data)
print(levene_test)
```

```{r}
#mô hình anova

model_2 <- aov(P_B_Frequency ~nb_of_Cores *Vertical_Segment, data = data)
summary(model_2)
```

#Hồi Quy Bội 
```{r}
modelR <- lm(P_B_Frequency~TDP+nb_of_Cores+nb_of_Threads+Lithography+Launch_Year+M_Memory_Size+Instruction_Set,data=data)
summary(modelR)
```

```{r}
car::vif(modelR)
```

```{r}
confint(modelR)
```

```{r}
plot(modelR)
```
#--------------------

#Hồi quy Ridge
```{r}
library(glmnet)
```
```{r}
xv<-as.matrix(data[,c('TDP', 'nb_of_Threads', 'nb_of_Cores', 'Lithography', 'Launch_Year', 'M_Memory_Size','Instruction_Set')])
```
```{r}
yv<-data$P_B_Frequency
Rmodel<-glmnet(x=xv,y=yv,alpha=0)
cv_model <- cv.glmnet(x=xv, y=yv, alpha = 0)

#find optimal lambda value that minimizes test MSE
best_lambda <- cv_model$lambda.min
best_lambda
```



```{r}
plot(cv_model)
```

```{r}
R_model<-glmnet(x=xv,y=yv,alpha=0,lambda=best_lambda)
coeffients<-coef(R_model)
coeffients
```

